### ISSUE TITLE
ionic serve 或者 ionic run android 或者 ionic run ios报错

### ISSUE THREAD

**Issue by TakWolf** [XueRainey/Ioniclub#10]
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(8,14): Error TS2300: Duplicate identifier 'PropertyKey'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(11,5): Error TS2300: Duplicate identifier 'done'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(12,5): Error TS2300: Duplicate identifier 'value'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(250,5): Error TS2300: Duplicate identifier 'EPSILON'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(285,5): Error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(292,5): Error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(348,5): Error TS2300: Duplicate identifier 'flags'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(500,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(563,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(572,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(583,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(592,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(607,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(621,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(8,14): Error TS2300: Duplicate identifier 'PropertyKey'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(11,5): Error TS2300: Duplicate identifier 'done'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(12,5): Error TS2300: Duplicate identifier 'value'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(250,5): Error TS2300: Duplicate identifier 'EPSILON'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(285,5): Error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(292,5): Error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(348,5): Error TS2300: Duplicate identifier 'flags'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(500,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(563,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(572,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(583,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(592,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(607,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(621,5): Error TS2300: Duplicate identifier 'prototype'.

**Comment by TakWolf** [comment]
这个问题还是存在，拉去的是最新的分支https://github.com/XueRainey/Ioniclub/commit/ee549c9bf7f6b823c65e6861a17835bf11af9f7d

虽然会报错，但是这个错误不会影响程序运行，各种插件也运行正常。

![image](https://cloud.githubusercontent.com/assets/6064962/14632732/dc35ff5e-064c-11e6-9c05-c6e66bbbbbd7.png)

typescript环境都有，typings install 这一步也能正常执行

**Comment by RaineySpace** [comment]
@TakWolf 已修复，请拉取最新代码，或者尝试删除typings目录，并重新执行typings install
