### ISSUE TITLE
关于 ionic plugin install 和 cordova 插件安装顺序的问题

### ISSUE THREAD

**Issue by TakWolf** [XueRainey/Ioniclub#11]
安装readme的步骤执行貌似存在问题。

先安装ionic plugin install会提示没安装任何插件

执行
ionic platform add android 或者 ionic platform add ios 之后再执行
ionic plugin install 才会安装插件

去查了一下，
cordova中添加了新平台，需要重新cordova install plugin
因为插件是安装在平台自己的目录下的，不是全局的

**Comment by TakWolf** [comment]
贴一下完整的步骤：

首次运行：
TakWolfdeMacBook-Pro:Ioniclub takwolf$ ionic plugin install
WARN: ionic.config.js has been deprecated, you can remove it.
No plugins added. Use `cordova plugin add <plugin>`.

安装平台后再运行：
TakWolfdeMacBook-Pro:Ioniclub takwolf$ ionic platform add android
WARN: ionic.config.js has been deprecated, you can remove it.
Adding android project...
Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: io.ionic.starter
    Name: Ioniclub
    Activity: MainActivity
    Android target: android-23
Android project created with cordova-android@5.1.1
Running command: /Users/takwolf/Clone/Ioniclub/hooks/after_prepare/010_add_platform_class.js /Users/takwolf/Clone/Ioniclub
add to body class: platform-android
Discovered plugin "cordova-plugin-device" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-device@~1.1.1" via npm
Installing "cordova-plugin-device" for android
Discovered plugin "cordova-plugin-console" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-console@~1.0.2" via npm
Installing "cordova-plugin-console" for android
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@~1.2.1" via npm
Installing "cordova-plugin-whitelist" for android

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do _not_ need this plugin since the whitelist will be built in.

Discovered plugin "cordova-plugin-splashscreen" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-splashscreen@~3.2.1" via npm
Installing "cordova-plugin-splashscreen" for android
Discovered plugin "cordova-plugin-statusbar" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-statusbar@~2.1.2" via npm
Installing "cordova-plugin-statusbar" for android
Discovered plugin "ionic-plugin-keyboard" in config.xml. Installing to the project
Fetching plugin "ionic-plugin-keyboard@~2.0.1" via npm
Installing "ionic-plugin-keyboard" for android
Discovered plugin "cordova-plugin-x-toast" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-x-toast@~2.5.0" via npm
Installing "cordova-plugin-x-toast" for android
Discovered plugin "phonegap-plugin-barcodescanner" in config.xml. Installing to the project
Fetching plugin "phonegap-plugin-barcodescanner@~4.1.0" via npm
Installing "phonegap-plugin-barcodescanner" for android
Saving platform to package.json file
TakWolfdeMacBook-Pro:Ioniclub takwolf$ ionic plugin install
WARN: ionic.config.js has been deprecated, you can remove it.
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-toast 2.5.0 "Toast"
ionic-plugin-keyboard 2.0.1 "Keyboard"
phonegap-plugin-barcodescanner 4.1.0 "BarcodeScanner"

**Comment by RaineySpace** [comment]
cordova在添加平台的时候，自动安装，所以Ionic install plugin确实不需要，已经修改，谢谢提醒
