### ISSUE TITLE
@[loginname] 协议生成的连接点击无效并闪退

### ISSUE THREAD

**Issue by TakWolf** [XueRainey/Ioniclub#12]
这个问题和 https://github.com/XueRainey/Ioniclub/issues/6 类似

nodeclub解析@[loginname]

协议生成的连接格式是 

```
<a href="/user/loginname">loginname</a>
```

在浏览器端会自动补全host，在移动端会补全到本地文件协议而产生错误，因此这个连接需要做兼容处理。
![screenshot_2016-04-19-19-22-23](https://cloud.githubusercontent.com/assets/6064962/14637745/e8083266-0665-11e6-8844-6516486707d2.png)

**Comment by TakWolf** [comment]
另外有一个地方不同理解的就是，点击什么样的连接是在本地进行路由，什么样的连接是打开外部浏览器？

**Comment by RaineySpace** [comment]
@TakWolf 好的，有关协议的问题，我会近期找时间处理一下。
