### ISSUE TITLE
执行 ionic plugin install 会报错，但是忽略也可以成功启动

### ISSUE THREAD

**Issue by TakWolf** [XueRainey/Ioniclub#5]
![image](https://cloud.githubusercontent.com/assets/6064962/14585507/8770c1ae-04ab-11e6-918f-cad01df7bce3.png)

**Comment by TakWolf** [comment]
运行Android也会报错，但忽略也会成功启动
![image](https://cloud.githubusercontent.com/assets/6064962/14585680/b71eee72-04af-11e6-9050-d2611b97c297.png)

**Comment by TakWolf** [comment]
运行iOS和android报相同的错误，这个是个啥问题啊

**Comment by XueRainey** [comment]
要全局安装cordova

**Comment by RaineySpace** [comment]
要全局安装cordova

**Comment by TakWolf** [comment]
@XueRainey  拉取最新的分之，运行的时候还是报错，这个跟之前一样，还是没解决

TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(8,14): Error TS2300: Duplicate identifier 'PropertyKey'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(11,5): Error TS2300: Duplicate identifier 'done'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(12,5): Error TS2300: Duplicate identifier 'value'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(250,5): Error TS2300: Duplicate identifier 'EPSILON'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(285,5): Error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(292,5): Error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(348,5): Error TS2300: Duplicate identifier 'flags'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(500,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(563,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(572,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(583,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(592,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(607,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/es6-shim.d.ts(621,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(8,14): Error TS2300: Duplicate identifier 'PropertyKey'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(11,5): Error TS2300: Duplicate identifier 'done'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(12,5): Error TS2300: Duplicate identifier 'value'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(250,5): Error TS2300: Duplicate identifier 'EPSILON'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(285,5): Error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(292,5): Error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(348,5): Error TS2300: Duplicate identifier 'flags'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(500,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(563,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(572,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(583,5): Error TS2300: Duplicate identifier 'size'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(592,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(607,5): Error TS2300: Duplicate identifier 'prototype'.
TypeScript error: typings/main/ambient/es6-shim/index.d.ts(621,5): Error TS2300: Duplicate identifier 'prototype'.

**Comment by TakWolf** [comment]
https://github.com/XueRainey/Ioniclub/issues/10

问题已移动

**Comment by TakWolf** [comment]
https://github.com/XueRainey/Ioniclub/issues/11

问题已移动
