### ISSUE TITLE
客户端部分发现的一些问题

### ISSUE THREAD

**Issue by TakWolf** [XueRainey/Ioniclub#7]
点击扫描二维码无反应，是因为这块还没做吗？

手机型号是：new noto x 2014 - XT1085 , Android 5.1

补充：应该是没做，iOS上也不好使

**Comment by TakWolf** [comment]
另外未登录状态缺少判断，没登录的情况下，发帖和回复都能点开，也能点发送，但是最终效果就没有提示，是内容都丢失了

**Comment by TakWolf** [comment]
Android的交互上有两点问题：

1.我在任何状态下都可以打开侧滑菜单，即使是在主题内容页面，我不确定这是个BUG还是就这么设计的？

2.Android设备有返回键，这个没做适配，有的时候操作习惯直接点了返回物理键，结果退出APP了

补充：在iOS上这个问题也存在，而且跟滑动返回有冲突，看图：

![img_0078](https://cloud.githubusercontent.com/assets/6064962/14585891/9104e594-04b8-11e6-8543-93e06aa9a09b.PNG)

**Comment by RaineySpace** [comment]
1. 点击扫描二维码无反应，是因为这块还没做吗？
   
    回复：因为你cordova插件没有安装到你的开发环境中，所以在打包程序的时候，并不会把cordova插件打包进去，所以，点击才不会有反应。
2. 另外未登录状态缺少判断，没登录的情况下，发帖和回复都能点开，也能点发送，但是最终效果就没有提示，是内容都丢失了
   
   回复：消息通知的判断加了，发帖和回复忘记判断了，谢谢提醒。
3. 如上
   
   回复：侧滑功能，我原本的设定是只有首页可以滑动，其他页面侧滑返回，代码还没有加上去。

**Comment by TakWolf** [comment]
https://github.com/XueRainey/Ioniclub/issues/5

 所以上面这个问题，是因为我的cordova的环境吗？

我确实忘记安装cordova了
